import { Metadata } from "next";
import { notFound } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { postsEn, postsVi } from "@/data/posts";
import BlogDetailContent from "./BlogDetailContent";

interface Props {
  params: Promise<{ slug: string }>;
}

// ── Next.js Dynamic SEO Metadata Generator (Server-side) ──
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = postsEn.find((p) => p.slug === slug) || postsVi.find((p) => p.slug === slug);

  if (!post) return {};

  const fullUrl = `https://vubaokhanh.tech/blog/${slug}`;

  return {
    title: `${post.title} | Vũ Bảo Khanh Blog`,
    description: post.description,
    keywords: post.tags,
    alternates: {
      canonical: fullUrl,
    },
    openGraph: {
      type: "article",
      locale: "vi_VN",
      alternateLocale: ["en_US"],
      url: fullUrl,
      title: post.title,
      description: post.description,
      publishedTime: post.isoDate,
      authors: ["Vũ Bảo Khanh"],
      // og:image is auto-injected by Next.js from opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
      creator: "@vubaokhannh",
      // twitter:image is auto-injected by Next.js from opengraph-image.tsx
    },
  };
}

// ── Prerender parameters for static exports ──
export async function generateStaticParams() {
  const slugs = Array.from(new Set([...postsEn.map((p) => p.slug), ...postsVi.map((p) => p.slug)]));
  return slugs.map((slug) => ({ slug }));
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;

  // Verify post existence
  const postEn = postsEn.find((p) => p.slug === slug);
  const postVi = postsVi.find((p) => p.slug === slug);

  if (!postEn && !postVi) {
    notFound();
  }

  // Fallback data if one language is missing
  const activePost = postEn || postVi;

  if (!activePost) {
    notFound();
  }

  // JSON-LD Article Schema (Dynamic generation for SEO crawlers)
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": `https://vubaokhanh.tech/blog/${activePost.slug}`,
    },
    "headline": activePost.title,
    "description": activePost.description,
    // Dynamic per-post OG image generated by opengraph-image.tsx
    "image": `https://vubaokhanh.tech/blog/${activePost.slug}/opengraph-image`,
    "datePublished": activePost.isoDate,
    "dateModified": activePost.isoDate,
    "author": {
      "@type": "Person",
      "name": activePost.author,
      "url": "https://vubaokhanh.tech",
      "sameAs": [
        "https://github.com/vubaokhannh",
        "https://linkedin.com/in/vubaokhannh",
      ],
    },
    "publisher": {
      "@type": "Organization",
      "name": "Vu Bao Khanh",
      "logo": {
        "@type": "ImageObject",
        "url": "https://vubaokhanh.tech/favicon.svg",
        "width": 48,
        "height": 48,
      },
    },
    "keywords": activePost.tags.join(", "),
    "inLanguage": ["en", "vi"],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <Navbar />
      <main className="min-h-screen bg-[#050505] text-white pt-32 pb-24 relative select-text">
        <div
          className="absolute inset-0 pointer-events-none"
          aria-hidden="true"
          style={{
            background:
              "radial-gradient(ellipse 50% 30% at 50% -10%, rgba(0,217,255,0.05) 0%, transparent 70%)",
          }}
        />

        <div className="container-custom max-w-5xl relative z-10 select-text">
          {/* Client-side content switcher based on active language */}
          <BlogDetailContent postEn={postEn} postVi={postVi} />
        </div>
      </main>
      <Footer />
    </>
  );
}
