import { Metadata } from "next";
import { notFound } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { getBlogPostBySlug, fetchRawBlogPosts } from "@/lib/data-fetchers";
import BlogDetailContent from "./BlogDetailContent";

export const revalidate = 60; // Revalidate page every 60 seconds (Incremental Static Regeneration)
export const dynamicParams = true; // Allow dynamic parameters for new blog posts created post-build


interface Props {
  params: Promise<{ slug: string }>;
}

// ── Next.js Dynamic SEO Metadata Generator (Server-side) ──
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const rawParams = await params;
  const slug = decodeURIComponent(rawParams.slug || "").trim();
  const [postEn, postVi] = await Promise.all([
    getBlogPostBySlug(slug, "en"),
    getBlogPostBySlug(slug, "vi"),
  ]);

  const hasEn = postEn && postEn.title && postEn.title.trim() !== "";
  const hasVi = postVi && postVi.title && postVi.title.trim() !== "";
  const post = hasEn ? postEn : (hasVi ? postVi : null);

  if (!post) return {};

  const fullUrl = `https://vubaokhanh.tech/blog/${encodeURIComponent(slug)}`;

  return {
    title: `${post.title} | Vũ Bảo Khanh Blog`,
    description: post.description,
    keywords: post.tags,
    alternates: {
      canonical: fullUrl,
    },
    openGraph: {
      type: "article",
      locale: "vi_VN",
      alternateLocale: ["en_US"],
      url: fullUrl,
      title: post.title,
      description: post.description,
      publishedTime: post.isoDate,
      authors: ["Vũ Bảo Khanh"],
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
      creator: "@vubaokhannh",
    },
  };
}

// ── Prerender parameters for static exports ──
export async function generateStaticParams() {
  const rawPosts = await fetchRawBlogPosts();
  return rawPosts.map((p) => ({ slug: p.slug }));
}

export default async function BlogPostPage({ params }: Props) {
  const rawParams = await params;
  const slug = decodeURIComponent(rawParams.slug || "").trim();

  // Verify post existence from database (parallel fetch)
  const [postEn, postVi] = await Promise.all([
    getBlogPostBySlug(slug, "en"),
    getBlogPostBySlug(slug, "vi"),
  ]);

  const hasEn = postEn && postEn.title && postEn.title.trim() !== "";
  const hasVi = postVi && postVi.title && postVi.title.trim() !== "";

  if (!hasEn && !hasVi) {
    notFound();
  }

  // Fallback data if one language is missing
  const activePost = hasEn ? postEn : postVi;

  if (!activePost) {
    notFound();
  }

  // JSON-LD Article Schema (Dynamic generation for SEO crawlers)
  const dateModified = activePost.isoDate; // Will be updated when blog posts have updatedAt field
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": `https://vubaokhanh.tech/blog/${activePost.slug}`,
    },
    "headline": activePost.title,
    "description": activePost.description,
    // Dynamic per-post OG image generated by opengraph-image.tsx
    "image": `https://vubaokhanh.tech/blog/${activePost.slug}/opengraph-image`,
    "datePublished": activePost.isoDate,
    "dateModified": dateModified,
    "author": {
      "@type": "Person",
      "name": activePost.author,
      "url": "https://vubaokhanh.tech",
      "sameAs": [
        "https://github.com/vubaokhannh",
        "https://linkedin.com/in/vubaokhannh",
      ],
    },
    "publisher": {
      "@type": "Organization",
      "name": "Vu Bao Khanh",
      "logo": {
        "@type": "ImageObject",
        "url": "https://vubaokhanh.tech/favicon.svg",
        "width": 48,
        "height": 48,
      },
    },
    "keywords": activePost.tags.join(", "),
    "inLanguage": ["en", "vi"],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <Navbar />
      <main className="min-h-screen bg-[#050505] text-white pt-32 pb-24 relative select-text">
        <div
          className="absolute inset-0 pointer-events-none"
          aria-hidden="true"
          style={{
            background:
              "radial-gradient(ellipse 50% 30% at 50% -10%, rgba(0,217,255,0.05) 0%, transparent 70%)",
          }}
        />

        <div className="container-custom max-w-5xl relative z-10 select-text">
          {/* Client-side content switcher based on active language */}
          <BlogDetailContent postEn={postEn || undefined} postVi={postVi || undefined} />
        </div>
      </main>
      <Footer />
    </>
  );
}
